CSH_PREFIX_ENTRY = "setenv PREFIX ${.CURDIR}/tmp"
CSH_PORTSDIR_ENTRY = "setenv PORTSDIR ${.CURDIR}"
CSH_PKG_DBDIR_ENTRY = "setenv PKG_DBDIR ${.CURDIR}/db/pkg"
CSH_PORT_DBDIR_ENTRY = "setenv PORT_DBDIR ${.CURDIR}/db/ports"
CSH_LOCK_DIR_ENTRY = "setenv LOCK_DIR ${.CURDIR}/db/portslocks"

SH_PREFIX_ENTRY = "PREFIX=${.CURDIR}/tmp\; export PREFIX"
SH_PORTSDIR_ENTRY = "PORTSDIR=${.CURDIR}\; export PORTSDIR"
SH_PKG_DBDIR_ENTRY = "PKG_DBDIR=${.CURDIR}/db/pkg\; export PKG_DBDIR"
SH_PORT_DBDIR_ENTRY = "PORT_DBDIR=${.CURDIR}/db/ports\; export PORT_DBDIR"
SH_LOCK_DIR_ENTRY = "LOCK_DIR=${.CURDIR}/db/portslocks\; export LOCK_DIR"

list_env_info:
	@echo "=== Configuring project environment"
	@echo "=== The following variables are necassary for debugging of the 'Parallelization in the ports collection project'"
	@echo "=== Add the following lines to your ~/.cshrc and /.cshrc files"
	@echo "${CSH_PREFIX_ENTRY}"
	@echo "${CSH_PORTSDIR_ENTRY}"
	@echo "${CSH_PKG_DBDIR_ENTRY}"
	@echo "${CSH_PORT_DBDIR_ENTRY}"
	@echo "${CSH_LOCK_DIR_ENTRY}"
	@echo "=== Add the following lines to your ~/.shrc and /.shrc files"
	@echo "${SH_PREFIX_ENTRY}"
	@echo "${SH_PORTSDIR_ENTRY}"
	@echo "${SH_PKG_DBDIR_ENTRY}"
	@echo "${SH_PORT_DBDIR_ENTRY}"
	@echo "${SH_LOCK_DIR_ENTRY}"
	@echo "=== I would want to Add the following lines to your /etc/make.conf"
	@echo "_parv_WANT_PARALLEL_BUILD=1"
	@echo "_parv_DEFAULT_PAR_BUILDS_NUM= 3"
