PORTNAME=fake4
PORTVERSION=1.0
DISTFILES=fake-1.0.tar.gz
CATEGORIES=fake_ports


WRKSRC= ${WRKDIR}/fake-1.0

CONFLICTS= fake3-* fake-*

NOCLEANDEPENDS=

do-install:
	@echo "Port: "fake4" is installing now"
	@echo "Press any key to continue:"
	@read i

.include <bsd.port.mk>
